apiVersion: apps/v1
kind: Deployment
metadata:
  name: claims-service
  namespace: learnivo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claims-service
  template:
    metadata:
      labels:
        app: claims-service
    spec:
      containers:
        - name: claims-service
          image: ghcr.io/nerodelly/claims-service:IMAGE_TAG
          ports:
            - containerPort: 8088
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: learnivo-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: DB_NAME
              value: learnivo
            - name: EUREKA_HOST
              value: eureka-service
            - name: EUREKA_PORT
              value: "8761"
            - name: IP_ADDRESS
              value: claims-service
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: learnivo-secrets
                  key: RABBITMQ_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 8088
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8088
            initialDelaySeconds: 40
            periodSeconds: 20
