apiVersion: apps/v1
kind: Deployment
metadata:
  name: competition-service
  namespace: learnivo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: competition-service
  template:
    metadata:
      labels:
        app: competition-service
    spec:
      containers:
        - name: competition-service
          image: ghcr.io/nerodelly/competition-service:IMAGE_TAG
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: learnivo-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/competition_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: learnivo-secrets
                  key: SPRING_DATASOURCE_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 80
            periodSeconds: 20
