apiVersion: v1
kind: ConfigMap
metadata:
  name: learnivo-config
  namespace: learnivo
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-service:8761/eureka/"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
  CONFIG_SERVER_URL: "http://config-server:8888"
  USER_SERVICE_URL: "http://user-service:8085"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MySQLDialect"
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
