apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: learnivo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/nerodelly/user-service:IMAGE_TAG
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: learnivo-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/learnivo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: learnivo-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: KEYCLOAK_ISSUER_URI
              valueFrom:
                secretKeyRef:
                  name: learnivo-secrets
                  key: KEYCLOAK_ISSUER_URI
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 80
            periodSeconds: 20
