apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-service
  namespace: learnivo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class-service
  template:
    metadata:
      labels:
        app: class-service
    spec:
      containers:
        - name: class-service
          image: ghcr.io/nerodelly/class-service:IMAGE_TAG
          ports:
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: learnivo-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/class_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: learnivo-secrets
                  key: SPRING_DATASOURCE_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 80
            periodSeconds: 20
