apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: learnivo
spec:
  selector:
    app: api-gateway
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
