apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: learnivo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: ghcr.io/nerodelly/course-service:IMAGE_TAG
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: learnivo-config
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/course_service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: learnivo-secrets
                  key: SPRING_DATASOURCE_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 80
            periodSeconds: 20
