# ── class-service config ─────────────────────────────────────────────────────
server.port=9090

spring.datasource.url=jdbc:mysql://mysql-db:3306/class_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
