# ── club-event-service config ────────────────────────────────────────────────
server.port=8087

spring.datasource.url=jdbc:mysql://mysql-db:3306/learnivo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.sql.init.mode=never

# Feign target
user-service.url=http://user-service:8085
user-service.api.users=/api/users
user-service.api.health=/api/test/hello
