# ── user-service config ──────────────────────────────────────────────────────
server.port=8085

spring.datasource.url=jdbc:mysql://mysql-db:3306/learnivo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.jpa.properties.hibernate.format_sql=true

# Keycloak (Docker container name)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://learnivo-keycloak:8080/realms/learnivo

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672

# Recaptcha
recaptcha.secret.key=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
app.url=http://localhost:4200
