pipeline {
    agent any

    environment {
        IMAGE    = 'localhost:5000/user-service'
        REGISTRY = 'localhost:5000'
    }

    tools {
        maven 'Maven 3.9.6'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        // ── CI ────────────────────────────────────────────────────────────────
        stage('Compile') {
            steps {
                sh 'mvn compile -pl user-service -am -DskipTests -q'
            }
        }

        stage('Run tests') {
            steps {
                sh 'mvn test -pl user-service -Deureka.client.enabled=false -Dspring.cloud.config.enabled=false "-Dspring.autoconfigure.exclude=org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration,org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration" || true'
            }
            post {
                always {
                    junit allowEmptyResults: true,
                          testResults: 'user-service/target/surefire-reports/*.xml'
                }
            }
        }

        // ── CD ────────────────────────────────────────────────────────────────
        stage('Build & Push Docker image') {
            when { branch 'mouhamedwork' }
            steps {
                sh "docker build -t ${IMAGE}:latest -t ${IMAGE}:${BUILD_NUMBER} -f user-service/Dockerfile ."
                sh "docker push ${IMAGE}:${BUILD_NUMBER}"
                sh "docker push ${IMAGE}:latest"
            }
        }

        stage('Deploy to Kubernetes') {
            when { branch 'mouhamedwork' }
            steps {
                withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG_FILE')]) {
                    sh "export KUBECONFIG=\$KUBECONFIG_FILE && sed 's|IMAGE_TAG|${BUILD_NUMBER}|g' k8s/user-service/deployment.yml | kubectl apply -f -"
                    sh "export KUBECONFIG=\$KUBECONFIG_FILE && kubectl apply -f k8s/user-service/service.yml"
                    sh "export KUBECONFIG=\$KUBECONFIG_FILE && kubectl rollout status deployment/user-service -n learnivo --timeout=180s"
                }
            }
        }
    }

    post {
        success { echo '✅ user-service pipeline passed' }
        failure { echo '❌ user-service pipeline failed' }
    }
}
