spring.application.name=claims-service
server.port=8089
spring.config.import=${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/learnivo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USER:hazem.ankoud10@gmail.com}
spring.mail.password=${SMTP_PASS:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.cloud.compatibility-verifier.enabled=false

# Actuator / Prometheus metrics
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
