apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: learnivo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: ghcr.io/nerodelly/config-server:IMAGE_TAG
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: learnivo-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 20
